version: '3.8'

services:
  api:
    build: ./ecom-api
    volumes:
      - ./ecom-api/:/app/
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always
    image: praveshpansari/ecom_api

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecom
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  postgres_data: {}
