"""empty message

Revision ID: 1747b9925518
Revises: 4aba2b253e3c
Create Date: 2022-11-08 19:38:26.441220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1747b9925518'
down_revision = '4aba2b253e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(), nullable=True))
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_column('product', 'qty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product', 'quantity')
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
